In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("50_Startups.csv")

In [3]:
df.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
df.tail()

    R&D Spend  Administration  Marketing Spend       State    Profit
45    1000.23       124153.04          1903.93    New York  64926.08
46    1315.46       115816.21        297114.46     Florida  49490.75
47       0.00       135426.92             0.00  California  42559.73
48     542.05        51743.15             0.00    New York  35673.41
49       0.00       116983.80         45173.06  California  14681.40

In [5]:
df.describe()

           R&D Spend  Administration  Marketing Spend         Profit
count      50.000000       50.000000        50.000000      50.000000
mean    73721.615600   121344.639600    211025.097800  112012.639200
std     45902.256482    28017.802755    122290.310726   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103730.875000    129300.132500   90138.902500
50%     73051.080000   122699.795000    212716.240000  107978.190000
75%    101602.800000   144842.180000    299469.085000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000

In [8]:
df.dtypes

R&D Spend          float64
Administration     float64
Marketing Spend    float64
State               object
Profit             float64
dtype: object

In [ ]:
#whERE there is misssing value it will show true
df.isnull()

    R&D Spend  Administration  Marketing Spend  State  Profit
0       False           False            False  False   False
1       False           False            False  False   False
2       False           False            False  False   False
3       False           False            False  False   False
4       False           False            False  False   False
5       False           False            False  False   False
6       False           False            False  False   False
7       False           False            False  False   False
8       False           False            False  False   False
9       False           False            False  False   False
10      False           False            False  False   False
11      False           False            False  False   False
12      False           False            False  False   False
13      False           False            False  False   False
14      False           False            False  False   False
15      False           False            False  False   False
16      False           False            False  False   False
17      False           False            False  False   False
18      False           False            False  False   False
19      False           False            False  False   False
20      False           False            False  False   False
21      False           False            False  False   False
22      False           False            False  False   False
23      False           False            False  False   False
24      False           False            False  False   False
25      False           False            False  False   False
26      False           False            False  False   False
27      False           False            False  False   False
28      False           False            False  False   False
29      False           False            False  False   False
30      False           False            False  False   False
31      False           False            False  False   False
32      False           False            False  False   False
33      False           False            False  False   False
34      False           False            False  False   False
35      False           False            False  False   False
36      False           False            False  False   False
37      False           False            False  False   False
38      False           False            False  False   False
39      False           False            False  False   False
40      False           False            False  False   False
41      False           False            False  False   False
42      False           False            False  False   False
43      False           False            False  False   False
44      False           False            False  False   False
45      False           False            False  False   False
46      False           False            False  False   False
47      False           False            False  False   False
48      False           False            False  False   False
49      False           False            False  False   False

In [10]:
df.isnull().any(axis=1)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
dtype: bool

In [11]:
df.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [12]:
df.fillna(0)

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [14]:
#filling the missing value with the mean of the colum
df["Marketing Spend"]=df["Marketing Spend"].fillna(df["Marketing Spend"].mean())
df

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [ ]:
df=df.rename(columns={"Profit":"total_profit"}) # rename the column name
# chnaing the index value or name
df=df.rename(index={[0][0]:12545})
df.head()

       R&D Spend  Administration  Marketing Spend       State  total_profit
12545  165349.20       136897.80        471784.10    New York     192261.83
1      162597.70       151377.59        443898.53  California     191792.06
2      153441.51       101145.55        407934.54     Florida     191050.39
3      144372.41       118671.85        383199.62    New York     182901.99
4      142107.34        91391.77        366168.42     Florida     166187.94

In [18]:
#chaning the datatype
df.dtypes

R&D Spend          float64
Administration     float64
Marketing Spend    float64
State               object
total_profit       float64
dtype: object

In [19]:
df["value_new"]=df["R&D Spend"].astype(int)
df

,R&D Spend,Administration,Marketing Spend,State,total_profit,value_new
12545,165349.20,136897.80,471784.10,New York,192261.83,165349
1,162597.70,151377.59,443898.53,California,191792.06,162597
2,153441.51,101145.55,407934.54,Florida,191050.39,153441
3,144372.41,118671.85,383199.62,New York,182901.99,144372
4,142107.34,91391.77,366168.42,Florida,166187.94,142107
5,131876.90,99814.71,362861.36,New York,156991.12,131876
6,134615.46,147198.87,127716.82,California,156122.51,134615
7,130298.13,145530.06,323876.68,Florida,155752.60,130298
8,120542.52,148718.95,311613.29,New York,152211.77,120542
9,123334.88,108679.17,304981.62,California,149759.96,123334
10,101913.08,110594.11,229160.95,Florida,146121.95,101913
11,100671.96,91790.61,249744.55,California,144259.40,100671
12,93863.75,127320.38,249839.44,Florida,141585.52,93863
13,91992.39,135495.07,252664.93,California,134307.35,91992
14,119943.24,156547.42,256512.92,Florida,132602.65,119943
15,114523.61,122616.84,261776.23,New York,129917.04,114523
16,78013.11,121597.55,264346.06,California,126992.93,78013
17,94657.16,145077.58,282574.31,New York,125370.37,94657
18,91749.16,114175.79,294919.57,Florida,124266.90,91749
19,86419.70,153514.11,0.00,New York,122776.86,86419
20,76253.86,113867.30,298664.47,California,118474.03,76253
21,78389.47,153773.43,299737.29,New York,111313.02,78389
22,73994.56,122782.75,303319.26,Florida,110352.25,73994
23,67532.53,105751.03,304768.73,Florida,108733.99,67532
24,77044.01,99281.34,140574.81,New York,108552.04,77044
25,64664.71,139553.16,137962.62,California,107404.34,64664
26,75328.87,144135.98,134050.07,Florida,105733.54,75328
27,72107.60,127864.55,353183.81,New York,105008.31,72107
28,66051.52,182645.56,118148.20,Florida,103282.38,66051
29,65605.48,153032.06,107138.38,New York,101004.64,65605
30,61994.48,115641.28,91131.24,Florida,99937.59,61994
31,61136.38,152701.92,88218.23,New York,97483.56,61136
32,63408.86,129219.61,46085.25,California,97427.84,63408
33,55493.95,103057.49,214634.81,Florida,96778.92,55493
34,46426.07,157693.92,210797.67,California,96712.80,46426
35,46014.02,85047.44,205517.64,New York,96479.51,46014
36,28663.76,127056.21,201126.82,Florida,90708.19,28663
37,44069.95,51283.14,197029.42,California,89949.14,44069
38,20229.59,65947.93,185265.10,New York,81229.06,20229
39,38558.51,82982.09,174999.30,California,81005.76,38558
40,28754.33,118546.05,172795.67,California,78239.91,28754
41,27892.92,84710.77,164470.71,Florida,77798.83,27892
42,23640.93,96189.63,148001.11,California,71498.49,23640
43,15505.73,127382.30,35534.17,New York,69758.98,15505
44,22177.74,154806.14,28334.72,California,65200.33,22177
45,1000.23,124153.04,1903.93,New York,64926.08,1000
46,1315.46,115816.21,297114.46,Florida,49490.75,1315
47,0.00,135426.92,0.00,California,42559.73,0
48,542.05,51743.15,0.00,New York,35673.41,542
49,0.00,116983.80,45173.06,California,14681.40,0

In [20]:
df.dtypes

R&D Spend          float64
Administration     float64
Marketing Spend    float64
State               object
total_profit       float64
value_new            int64
dtype: object

In [27]:
df

State
California    64657.117647
Florida       80723.500000
New York      76194.647059
Name: value_new, dtype: float64

In [29]:

#merging and joining dataset
df1=pd.DataFrame({"key":["a","b","c","d"],"value":[12,45,84,78]})
df2=pd.DataFrame({"key":["a","b","c","d"],"value":[78,82,25,43]})

In [30]:
df_merge=pd.merge(df1,df2,on="key",how="inner")

In [31]:
df_merge

  key  value_x  value_y
0   a       12       78
1   b       45       82
2   c       84       25
3   d       78       43