In [1]:
import pandas as pd

In [2]:
#series 
#pandas series is one dimension array like onject that can hold any data type 
data=[1,85,9,6,54]
series=pd.Series(data)
print(series)

0     1
1    85
2     9
3     6
4    54
dtype: int64

In [5]:
# create the series from dictionary

data={"a":12,"b":45,"c":78}
series_dict=pd.Series(data)
print(series_dict)

a    12
b    45
c    78
dtype: int64

In [10]:
data=[12,5,6,48,56,8]
index=["a","b","c","d","E","F"]
series=pd.Series(data,index=index)
print(series)

a    12
b     5
c     6
d    48
E    56
F     8
dtype: int64

In [11]:
#dataframe
#create a dataframe from dictionary of list
data={"name":["irfan","humayun","attar"],
      "age":[12,5,2,],"city":["gulbarga","kalburgi","delhi"]}
df=pd.DataFrame(data)
print(df)

      name  age      city
0    irfan   12  gulbarga
1  humayun    5  kalburgi
2    attar    2     delhi

In [12]:
#create a dadtframe from list of dictionary
data=[{"name":"irfan","age":23,"city":"gul"},{"name":"irfan","age":23,"city":"gul"},{"name":"irfan","age":23,"city":"gul"}]
df=pd.DataFrame(data)
print(df)

    name  age city
0  irfan   23  gul
1  irfan   23  gul
2  irfan   23  gul

In [23]:
df=pd.read_csv("sales_data.csv")

In [25]:
df.head()

         date       Sales
0  2020-01-01  104.967142
1  2020-02-01  126.474500
2  2020-03-01  155.492441
3  2020-04-01  173.801727
4  2020-05-01  152.388308

In [26]:
df["date"]

0     2020-01-01
1     2020-02-01
2     2020-03-01
3     2020-04-01
4     2020-05-01
5     2020-06-01
6     2020-07-01
7     2020-08-01
8     2020-09-01
9     2020-10-01
10    2020-11-01
11    2020-12-01
12    2021-01-01
13    2021-02-01
14    2021-03-01
15    2021-04-01
16    2021-05-01
17    2021-06-01
18    2021-07-01
19    2021-08-01
20    2021-09-01
21    2021-10-01
22    2021-11-01
23    2021-12-01
24    2022-01-01
25    2022-02-01
26    2022-03-01
27    2022-04-01
28    2022-05-01
29    2022-06-01
30    2022-07-01
31    2022-08-01
32    2022-09-01
33    2022-10-01
34    2022-11-01
35    2022-12-01
Name: date, dtype: object

In [28]:
df.loc[0]
df.loc[0][0]

C:\Users\Asus\AppData\Local\Temp\ipykernel_6616\416620832.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][0]

'2020-01-01'

In [33]:
#accesing specific element
df.at[1,"date"]
#by row index and column index

'2020-02-01'

In [36]:
df.iat[2,1]  # row 2, column 1 (Sales column)

np.float64(155.49244128451457)

In [38]:
df.head(3)

         date       Sales
0  2020-01-01  104.967142
1  2020-02-01  126.474500
2  2020-03-01  155.492441

In [42]:
#data manipulation with dataframe

#addding column
df["salary"] = [10000] * 36
df
df.drop("salary",axis=1)

          date       Sales
0   2020-01-01  104.967142
1   2020-02-01  126.474500
2   2020-03-01  155.492441
3   2020-04-01  173.801727
4   2020-05-01  152.388308
5   2020-06-01  136.944345
6   2020-07-01  132.934985
7   2020-08-01  102.674347
8   2020-09-01   74.861129
9   2020-10-01   81.139886
10  2020-11-01   80.635981
11  2020-12-01  101.771274
12  2021-01-01  136.705337
13  2021-02-01  143.010055
14  2021-03-01  166.052092
15  2021-04-01  187.234268
16  2021-05-01  178.887245
17  2021-06-01  176.713902
18  2021-07-01  142.348331
19  2021-08-01  115.162677
20  2021-09-01  128.498075
21  2021-10-01  107.742237
22  2021-11-01  120.231155
23  2021-12-01  126.466804
24  2022-01-01  163.127601
25  2022-02-01  197.537797
26  2022-03-01  206.077049
27  2022-04-01  230.899837
28  2022-05-01  217.294883
29  2022-06-01  204.940205
30  2022-07-01  179.697220
31  2022-08-01  182.094210
32  2022-09-01  147.992329
33  2022-10-01  133.708605
34  2022-11-01  162.067036
35  2022-12-01  162.791564

In [44]:
#add value to column
df["sales"]=["sales"]+1

TypeError: can only concatenate list (not "int") to list